### ISSUE TITLE
TFDM sample - slow render times

### ISSUE THREAD

**Issue by Kyozon** [shocker-0x15/GfxExp#12]
Hi there,

I just built the TFDM sample you've showcased on Twitter: https://twitter.com/Shocker_0x15/status/1725546495423001032?s=20

And for some reason my render time is a lot slower compared to yours. I have tested both RTX 4090 and RTX 3090, with 180ms and 250ms render times, respectively. 

![CUDA_perf](https://github.com/shocker-0x15/GfxExp/assets/35878729/64901cb0-9913-440d-acc4-1dacb1d3cdd7)

NVIDIA Driver: 546.17
RTX 4090 & 3090 GPUs
Windows 11 23H2
Visual Studio Community 17.7.6
OptiX 8.0.0
CUDA 12.3.1 toolkit

Thanks for sharing this excellent work.

**Comment by shocker-0x15** [comment]
Hi, could you tell me the frame time of out of the box? so, no command line options.
For me the time is 20.8 [ms] with RTX 4080,
![image](https://github.com/shocker-0x15/GfxExp/assets/4602478/345b25dd-37e5-4ad4-806a-b0fc11f8f22e)

**Comment by shocker-0x15** [comment]
Of course, in Release build.

**Comment by Kyozon** [comment]
Oh, wow I built it in Debug mode previously. Sorry about that, now my 3090 numbers look at closer to yours. 

![3090_TFDM_Release](https://github.com/shocker-0x15/GfxExp/assets/35878729/93f95fa3-e99b-4615-a2c1-e336d2d24053)

**Comment by Kyozon** [comment]
Oh, wow I built it in Debug mode previously. Sorry about that, now my 3090 numbers look at closer to yours.

![3090_TFDM_Release](https://github.com/shocker-0x15/GfxExp/assets/35878729/8f529d58-4826-4585-ae6c-de74d1f3127c)
