### ISSUE TITLE
Run-time NRC crash: cuGraphicsGLRegisterImage()

### ISSUE THREAD

**Issue by pantelis-kan** [shocker-0x15/GfxExp#7]
The VS solution compiles just fine, but when I run neural_radiance_cache.exe with the correct parameters, I get the following error:
`Error: CUDA call (cuGraphicsGLRegisterImage(&m_cudaGfxResource, glTexID, GL_TEXTURE_2D, flags) ) failed with error: 'OS call failed or operation not supported on this OS' (...\GfxExp\utils\cuda_util.cpp:677)`

As a note, the program is able to identify my RTX 3060 card.

**Comment by shocker-0x15** [comment]
Hi,
What driver version are you using?
Do you attempt to try to launch the program via remote desktop?

**Comment by pantelis-kan** [comment]
Hi! I'm using the latest driver from Nvidia Geforce Experience. 
No I'm using it from my own PC with Windows 10, latest updates.

The error occures both in Release and Debug mode. It has something to do with Cuda/GL interoperability, but it is very strange that I'm getting this error.

**Comment by shocker-0x15** [comment]
Are you using some laptop with iGPU and dGPU (RTX 3060 here)?

**Comment by pantelis-kan** [comment]
No, I have a desktop.

**Comment by shocker-0x15** [comment]
Can you run the other programs (e.g. path_tracing)?
Does the issue happen only with NRC?

**Comment by pantelis-kan** [comment]
I recompiled and it worked this time. Thanks!
