### ISSUE TITLE
How to set the correct commond line parameters?

### ISSUE THREAD

**Issue by RenieWell** [shocker-0x15/GfxExp#8]
For the neural radiance caching example, the paths of the mesh and texture are required in the No.808 line of "neural_radiance_caching_main.cpp" with function "parseCommandline(argc, argv);". However, I failed several times in giving the file path by command line parameters.
Can you give an example of the command line parameters? like "-inst /ZeroDay_v1/MEASURE_ONE/MEASURE_ONE.fbx"

**Comment by shocker-0x15** [comment]
Hello there,
in my case (launching the app from the VS 2022, the working directory is set to the `$(ProjectDir)`), the command line options look like:
`-position-encoding tri-wave -num-hidden-layers 5 -learning-rate 0.01 -cam-pos 13.0 0 0 -cam-yaw -90 -name scene -obj ../../assets/ZeroDay_v1/MEASURE_SEVEN/MEASURE_SEVEN_COLORED_LIGHTS.fbx 1.0 simple_pbr -brightness 2.0 -inst scene`

You can find example command line options for each project at the top comments in the main.cpp.

**Comment by RenieWell** [comment]
It works! Thanks a lot!
