### ISSUE TITLE
Q: Passing texture objects

### ISSUE THREAD

**Issue by ib00** [shocker-0x15/GfxExp#9]
Is it possible to pass Texture objects to CUDA kernels
or are only Buffers (typed and untyped) supported?

**Comment by shocker-0x15** [comment]
This does not look a question for this project, just an easy CUDA question. And yes you can.

**Comment by ib00** [comment]
I am referring to 'callKernel' function in 'utils/cuda_util.h'
When you expand argument pack, it seems the only types supported are buffers.
Yes?

**Comment by shocker-0x15** [comment]
cudau::Buffer is not the native type, so its pointer needs to be extracted. callKernel supports automatic extraction for better usage. CUtexObj is the native type, no need special handling.
